version: '3'
services:
  mongo:
    image: mongo
    restart: always
    networks:
      - local
    volumes:
      - ./volumes/mongo:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - local
    ports:
      - 8888:8081
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
  api:
    build:
      context: ./api
    restart: always
    depends_on:
      - mongo
    networks:
      - local
    links:
      - mongo
    command: node server.js
    ports:
      - 3000:3000
  streaming:
    build:
      context: ./streaming
    restart: always
    networks:
      - local
    depends_on:
      - api
      - icecast
    ports:
      - 8089:8000
    command: node index.js
    volumes:
      - ./tracks:/app/tracks
  icecast:
    image: infiniteproject/icecast
    build:
      context: .
      dockerfile: Dockerfile.icecast
    ports:
      - 8002:8000
    networks:
      - local
    volumes:
      - ./volumes/logs:/var/log/icecast
    environment:
      ICECAST_SOURCE_PASSWORD: changeme
      ICECAST_ADMIN_PASSWORD: changeme
      ICECAST_PASSWORD: changeme
      ICECAST_RELAY_PASSWORD: changeme
      ICECAST_ADMIN_USERNAME: admin
      ICECAST_ADMIN_EMAIL: admin@admin.com
      ICECAST_HOSTNAME: localhost
      ICECAST_LOCATION: Moon
      ICECAST_MAX_CLIENTS: 40
      ICECAST_MAX_SOURCES: 10
networks:
  local: